---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Bajando Pagina
      shell: /etc/ansible/BonusConti/pag_mantenimiento_down.sh 
    - name: Notificacion Telegram 
      shell: /etc/ansible/BonusConti/smsDOWN.sh
    - name: Notificacion SMS
      shell: /etc/ansible/BonusConti/notificacionLoteDown.sh

- hosts: ContiJbossWeb
  tasks:
    - name: Bajando Jboss Web
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ContiJbossTrans
  tasks:
    - name: Bajando Jboss Trans
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ContiJbossGX
  tasks:
    - name: Bajando Jboss GX
      command: killall -9 java
- hosts: ContiJbossBC
  tasks:
    - name: Bajando Jboss BC
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ContiJbossArchivos
  tasks:
    - name: Bajando Jboss Archivos
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ContiJbossESBTRA
  tasks:
    - name: Bajando Jboss ESBTRA
      service:
       name: jboss-eap-rhel
       state: stopped 
