---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Bajando Pagina
      shell: /etc/ansible/BonusConti/pag_mantenimiento_down.sh 
    - name: Notificacion Telegram 
      shell: /etc/ansible/BonusConti/smsDOWN.sh
    - name: Notificacion SMS
      shell: /etc/ansible/BonusConti/notificacionLoteDown.sh
    - name: Bajando Jboss Web
      shell: ansible-playbook /etc/ansible/BonusConti/ContiJbossWebStop.yml
    - name: Bajando Jboss Trans
      shell: ansible-playbook /etc/ansible/BonusConti/ContiJbossTransStop.yml
    - name: Bajando Jboss GX
      shell: ansible-playbook /etc/ansible/BonusConti/ContiJbossGXStop.yml
    - name: Bajando Jboss BC
      shell: ansible-playbook /etc/ansible/BonusConti/ContiJbossBCStop.yml
    - name: Bajando Jboss Archivos
      shell: ansible-playbook /etc/ansible/BonusConti/ContiJbossArchivosStop.yml
    - name: Bajando Jboss ESBTRA
      shell: ansible-playbook /etc/ansible/BonusConti/ContiJbossESBTRAStop.yml
   
