---
- hosts: ContiJbossGX
  tasks:
  - name: Habilitar el contexto de los JbossWeb Conti en el Apache 10.23.1.106
    command: curl http://10.23.1.106:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}
- hosts: ContiJbossGX
  tasks:
  - name: Habilitar el contexto de los JbossWeb Conti en el Apache 10.23.1.111
    command: curl http://10.23.1.111:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}
- hosts: ContiJbossWeb
  tasks:
  - name: Habilitar el contexto de los JbossWeb Conti en el Apache 10.23.1.136
    command: curl http://10.23.1.136:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}
- hosts: ContiJbossWeb
  tasks:
  - name: Habilitar el contexto de los JbossWeb Conti en el Apache 10.23.1.136
    command: curl http://10.23.1.136:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}
- hosts: ContiJbossTrans
  tasks:
  - name: Habilitar el contexto de los JbossWeb Conti en el Apache 10.23.1.22
    command: curl http://10.23.1.22:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}
- hosts: ContiJbossTrans
  tasks:
  - name: Habilitar el contexto de los JbossWeb Conti en el Apache 10.23.1.24
    command: curl http://10.23.1.24:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}
...

