---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Bajando Pagina
      shell: /etc/ansible/BonusConti/pag_mantenimiento_down.sh 
    - name: Notificacion Telegram 
      shell: /etc/ansible/BonusConti/smsDOWN.sh
    - name: Notificacion SMS
      shell: /etc/ansible/BonusConti/notificacionLoteDown.sh
   
